/* table header info */
SELECT
     CollectTimeStamp, 
     QueryID ( Format '--Z(17)9'),
     UserID, 
     Cast(UserName AS CHAR(30)) (Named UserName),
     Cast(DefaultDatabase AS CHAR(30)) (Named DefaultDatabase),
     Cast(AcctString AS CHAR(30)) (Named AcctString),
     Cast(ExpandAcctString AS CHAR(30)) (Named ExpandAcctString),
     SessionID, 
     LogicalHostID, 
     RequestNum, 
     InternalRequestNum, 
     TxnUniq,
     LockLevel,
     LogonDateTime, 
     AcctStringTime,
     AcctStringHour,
     AcctStringDate,
     LogonSource,
     AppID, 
     ClientID,
     ClientAddr,
     QueryBand,
     ProfileID,
     StartTime, 
     FirstStepTime,
     FirstRespTime,
     ((firstresptime - starttime) HOUR(4) TO SECOND) (Named ElapsedTime),
     NumSteps,
     NumStepswPar,
     MaxStepsInPar,
     NumResultRows,
     TotalIOCount,
     AMPCPUTime (Format 'ZZ,ZZZ,ZZ9.999'),
     ParserCPUTime (Format 'ZZ,ZZZ,ZZ9.999'),
     UtilityByteCount,
     UtilityRowCount,
     Errorcode,
     Cast(Substring(Translate(ErrorText USING UNICODE_TO_LOCALE WITH ERROR) FROM 1 FOR 255)
          AS CHAR(255)) (Named ErrorText),
     WarningOnly,
     AbortFlag,
     CacheFlag,
     StatementType,
     StatementGroup,
     QueryText,
     NumOfActiveAMPs,
     MaxAmpCPUTime (Format 'ZZ,ZZZ,ZZ9.999'), 
     MaxCPUAmpNumber,
     MinAmpCPUTime (Format 'ZZ,ZZZ,ZZ9.999'), 
     MaxAmpIO,
     MaxIOAmpNumber,
     MinAmpIO,
     SpoolUsage,
     LSN,
     EstResultRows,
     EstProcTime (Format 'ZZ,ZZZ,ZZ9.999'),
     EstMaxRowCount,
     TDWMEstMemUsage (Format 'ZZ,ZZZ,ZZ9.999')(Named TDWMEstMemUsage),
     AMPCPUTimeNorm (Format 'ZZ,ZZZ,ZZ9.999'),
     ParserCPUTimeNorm (Format 'ZZ,ZZZ,ZZ9.999'),  
     MaxAmpCPUTimeNorm (Format 'ZZ,ZZZ,ZZ9.999'),
     MaxCPUAmpNumberNorm, 
     MinAmpCPUTimeNorm (Format 'ZZ,ZZZ,ZZ9.999'),
     ParserExpReq (Format 'ZZ,ZZZ,ZZ9.999'),
     Cast(ProxyUser AS CHAR(30)) (Named ProxyUser),
     Cast(ProxyRole AS CHAR(30)) (Named ProxyRole),
     SessionTemporalQualifier,
     CalendarName,
     CPUDecayLevel, 
     IODecayLevel,
     TacticalCPUException, 
     TacticalIOException,
     SeqRespTime (Format 'ZZ,ZZZ,ZZ9.999'),
     ReqIOKB (Format 'ZZ,ZZZ,ZZ9.999'),  
     ReqPhysIO (Format 'ZZ,ZZZ,ZZ9.999'),
     ReqPhysIOKB (Format 'ZZ,ZZZ,ZZ9.999'),
     DataCollectAlg,
     CallNestingLevel,
     NumRequestCtx,
     KeepFlag,
     QueryReDriven,
     ReDriveKind,
     LastRespTime,
     DisCPUTime,
     Statements,
     DisCPUTimeNorm,
     TxnMode,
     RequestMode,
     DBQLStatus,
     NumFragments,
     VHLogicalIO,
     VHPhysIO,
     VHLogicalIOKB,
     VHPhysIOKB,
     LockDelay,
     CheckpointNum,
     UtilityInfoAvailable,
     UnitySQL,
     ThrottleBypassed, 
     IterationCount,
     MaxStepMemory,
  
 FROM DBC.DBQLogTbl;